from enum import Enum

class ODriveGpioMode(Enum):
    GPIO_MODE_DIGITAL = 0
    GPIO_MODE_DIGITAL_PULL_UP = 1
    GPIO_MODE_DIGITAL_PULL_DOWN = 2
    GPIO_MODE_ANALOG_IN = 3
    GPIO_MODE_UART_A = 4
    GPIO_MODE_UART_B = 5
    GPIO_MODE_UART_C = 6
    GPIO_MODE_CAN_A = 7
    GPIO_MODE_I2C_A = 8
    GPIO_MODE_SPI_A = 9
    GPIO_MODE_PWM = 10
    GPIO_MODE_ENC0 = 11
    GPIO_MODE_ENC1 = 12
    GPIO_MODE_ENC2 = 13
    GPIO_MODE_MECH_BRAKE = 14
    GPIO_MODE_STATUS = 15
    GPIO_MODE_BRAKE_RES = 16
    GPIO_MODE_AUTO = 17

class ODriveStreamProtocolType(Enum):
    STREAM_PROTOCOL_TYPE_FIBRE = 0
    STREAM_PROTOCOL_TYPE_ASCII = 1
    STREAM_PROTOCOL_TYPE_STDOUT = 2
    STREAM_PROTOCOL_TYPE_ASCII_AND_STDOUT = 3
    STREAM_PROTOCOL_TYPE_OTHER = 4

class ODriveProtocol(Enum):
    PROTOCOL_NONE = 0x00000000
    PROTOCOL_SIMPLE = 0x00000001

class ODriveAxisState(Enum):
    AXIS_STATE_UNDEFINED = 0
    AXIS_STATE_IDLE = 1
    AXIS_STATE_STARTUP_SEQUENCE = 2
    AXIS_STATE_FULL_CALIBRATION_SEQUENCE = 3
    AXIS_STATE_MOTOR_CALIBRATION = 4
    AXIS_STATE_ENCODER_INDEX_SEARCH = 6
    AXIS_STATE_ENCODER_OFFSET_CALIBRATION = 7
    AXIS_STATE_CLOSED_LOOP_CONTROL = 8
    AXIS_STATE_LOCKIN_SPIN = 9
    AXIS_STATE_ENCODER_DIR_FIND = 10
    AXIS_STATE_HOMING = 11
    AXIS_STATE_ENCODER_HALL_POLARITY_CALIBRATION = 12
    AXIS_STATE_ENCODER_HALL_PHASE_CALIBRATION = 13
    AXIS_STATE_ANTICOGGING_CALIBRATION = 14

class ODriveControlMode(Enum):
    CONTROL_MODE_VOLTAGE_CONTROL = 0
    CONTROL_MODE_TORQUE_CONTROL = 1
    CONTROL_MODE_VELOCITY_CONTROL = 2
    CONTROL_MODE_POSITION_CONTROL = 3

class ODriveComponentStatus(Enum):
    COMPONENT_STATUS_NOMINAL = 0
    COMPONENT_STATUS_NO_RESPONSE = 1
    COMPONENT_STATUS_INVALID_RESPONSE_LENGTH = 2
    COMPONENT_STATUS_PARITY_MISMATCH = 3
    COMPONENT_STATUS_ILLEGAL_HALL_STATE = 4
    COMPONENT_STATUS_POLARITY_NOT_CALIBRATED = 5
    COMPONENT_STATUS_PHASES_NOT_CALIBRATED = 6
    COMPONENT_STATUS_NUMERICAL_ERROR = 7
    COMPONENT_STATUS_MISSING_INPUT = 8
    COMPONENT_STATUS_RELATIVE_MODE = 9
    COMPONENT_STATUS_UNCONFIGURED = 10
    COMPONENT_STATUS_OVERSPEED = 11
    COMPONENT_STATUS_INDEX_NOT_FOUND = 12
    COMPONENT_STATUS_BAD_CONFIG = 13
    COMPONENT_STATUS_NOT_ENABLED = 14
    COMPONENT_STATUS_SPINOUT_DETECTED = 15

class ODriveError(Enum):
    ODRIVE_ERROR_NONE = 0x00000000
    ODRIVE_ERROR_INITIALIZING = 0x00000001
    ODRIVE_ERROR_SYSTEM_LEVEL = 0x00000002
    ODRIVE_ERROR_TIMING_ERROR = 0x00000004
    ODRIVE_ERROR_MISSING_ESTIMATE = 0x00000008
    ODRIVE_ERROR_BAD_CONFIG = 0x00000010
    ODRIVE_ERROR_DRV_FAULT = 0x00000020
    ODRIVE_ERROR_MISSING_INPUT = 0x00000040
    ODRIVE_ERROR_DC_BUS_OVER_VOLTAGE = 0x00000100
    ODRIVE_ERROR_DC_BUS_UNDER_VOLTAGE = 0x00000200
    ODRIVE_ERROR_DC_BUS_OVER_CURRENT = 0x00000400
    ODRIVE_ERROR_DC_BUS_OVER_REGEN_CURRENT = 0x00000800
    ODRIVE_ERROR_CURRENT_LIMIT_VIOLATION = 0x00001000
    ODRIVE_ERROR_MOTOR_OVER_TEMP = 0x00002000
    ODRIVE_ERROR_INVERTER_OVER_TEMP = 0x00004000
    ODRIVE_ERROR_VELOCITY_LIMIT_VIOLATION = 0x00008000
    ODRIVE_ERROR_POSITION_LIMIT_VIOLATION = 0x00010000
    ODRIVE_ERROR_WATCHDOG_TIMER_EXPIRED = 0x01000000
    ODRIVE_ERROR_ESTOP_REQUESTED = 0x02000000
    ODRIVE_ERROR_SPINOUT_DETECTED = 0x04000000
    ODRIVE_ERROR_BRAKE_RESISTOR_DISARMED = 0x08000000
    ODRIVE_ERROR_THERMISTOR_DISCONNECTED = 0x10000000
    ODRIVE_ERROR_CALIBRATION_ERROR = 0x40000000



class ProcedureResult(Enum):
    SUCCESS = 0  # The procedure finished without any faults.
    BUSY = 1  # The procedure has not yet finished.
    CANCELLED = 2  # The last procedure was cancelled by the user.
    DISARMED = 3  # A fault was encountered and the axis has been disarmed.
    NO_RESPONSE = 4  # The procedure component did not respond as expected.
    POLE_PAIR_CPR_MISMATCH = 5  # The values of motor.pole_pairs and/or inc_encoder0.cpr do not match measurements.
    PHASE_RESISTANCE_OUT_OF_RANGE = 6  # The measured motor phase resistance is outside of the plausible range.
    PHASE_INDUCTANCE_OUT_OF_RANGE = 7  # The measured motor phase inductance is outside of the plausible range.
    UNBALANCED_PHASES = 8  # The motor phase resistances are not balanced.
    INVALID_MOTOR_TYPE = 9  # The motor_type is not defined in the MotorType enum.
    ILLEGAL_HALL_STATE = 10  # Too many bad hall states detected during calibration.
    TIMEOUT = 11  # The operation timed out.
    HOMING_WITHOUT_ENDSTOP = 12  # Homing was requested without enabling the endstop.
    INVALID_STATE = 13  # The requested state must be a valid AxisState.
    NOT_CALIBRATED = 14  # The requested state could not be entered because the axis is not calibrated.
    NOT_CONVERGING = 15  # The calibration did not converge.
